/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::FileReferenceFactoryColumnTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFactoryColumnTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFactoryColumnTemplate

#include "GacStudioUIPartialClasses.h"

namespace ui
{
	class FileReferenceFactoryColumnTemplate : public ui::FileReferenceFactoryColumnTemplate_<ui::FileReferenceFactoryColumnTemplate>
	{
		friend class ui::FileReferenceFactoryColumnTemplate_<ui::FileReferenceFactoryColumnTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ui::FileReferenceFactoryColumnTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		FileReferenceFactoryColumnTemplate();
	};
}

#endif
