/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::FileReferenceFactoryEditorTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFactoryEditorTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFactoryEditorTemplate

#include "GacStudioUIPartialClasses.h"

namespace ui
{
	class FileReferenceFactoryEditorTemplate : public ui::FileReferenceFactoryEditorTemplate_<ui::FileReferenceFactoryEditorTemplate>
	{
		friend class ui::FileReferenceFactoryEditorTemplate_<ui::FileReferenceFactoryEditorTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ui::FileReferenceFactoryEditorTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		FileReferenceFactoryEditorTemplate(Ptr<vm::IStudioAddExistingFilesModel> OperationModel);
	};
}

#endif
