/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::FileReferenceFolderColumnTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFolderColumnTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceFolderColumnTemplate

#include "GacStudioUIPartialClasses.h"

namespace ui
{
	class FileReferenceFolderColumnTemplate : public ui::FileReferenceFolderColumnTemplate_<ui::FileReferenceFolderColumnTemplate>
	{
		friend class ui::FileReferenceFolderColumnTemplate_<ui::FileReferenceFolderColumnTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ui::FileReferenceFolderColumnTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		FileReferenceFolderColumnTemplate();
	};
}

#endif
