/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::FileReferenceNameColumnTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceNameColumnTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_GacStudioUI_FileReferenceNameColumnTemplate

#include "GacStudioUIPartialClasses.h"

namespace ui
{
	class FileReferenceNameColumnTemplate : public ui::FileReferenceNameColumnTemplate_<ui::FileReferenceNameColumnTemplate>
	{
		friend class ui::FileReferenceNameColumnTemplate_<ui::FileReferenceNameColumnTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ui::FileReferenceNameColumnTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		FileReferenceNameColumnTemplate();
	};
}

#endif
