<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Lua Syntax: version 0.8</string>
	<key>fileTypes</key>
	<array>
		<string>moe</string>
	</array>
	<key>name</key>
	<string>Moescript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.moescript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.moescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.moescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.moescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.moescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[(=+)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.moescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.moescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.heredoc.moescript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.moescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`g?i?m?x?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.moescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.regexp.moescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\u[a-fA-F0-9]{4}|\\\S</string>
					<key>name</key>
					<string>constant.character.escape.moescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.moescript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.moescript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.moescript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\S</string>
					<key>name</key>
					<string>constant.character.escape.moescript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\\s</string>
					<key>end</key>
					<string>\\</string>
					<key>name</key>
					<string>constant.character.escape.moescript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.moescript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--|//).*</string>
			<key>name</key>
			<string>comment.line.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|@|::)\b(break|else|for|if|return|repeat|while|until|when|where|try|catch|piecewise|case|otherwise)\b(?![ \t]*:)</string>
			<key>name</key>
			<string>keyword.control.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|@|::)\b(function|def|var)\b(?![ \t]*:)</string>
			<key>name</key>
			<string>keyword.control.declare.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|@|::)\b(do|resend|new|wait|throw)\b(?![ \t]*:)</string>
			<key>name</key>
			<string>constant.language.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|@|::)\b(this|arguments)\b(?![ \t]*:)</string>
			<key>name</key>
			<string>variable.language.semiargs.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|@|::)\b(and|or|is|as|not|negate)\b(?![ \t]*:)</string>
			<key>name</key>
			<string>keyword.operator.moescript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)|&amp;&amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.moescript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.moescript</string>
	<key>uuid</key>
	<string>07e5a3c2-d7e4-4a2f-ac96-57438cd72f03</string>
</dict>
</plist>
